name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dc: [dmd-latest, ldc-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.dc }}
      - run: dub test --compiler=${{ env.DC }}
      - run: dub build --compiler=${{ env.DC }}
        working-directory: example
